---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "snappcloud-status-backend.fullname" . }}
  labels:
    {{- include "snappcloud-status-backend.labels" . | nindent 4 }}
data:
  values.yml: | {{- .Values.values | toYaml | nindent 4 }}

