---
{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "snappcloud-status-backend.fullname" $ }}
spec:
  host: "{{ include "snappcloud-status-backend.fullname" $ }}.{{ .Release.Namespace }}.apps.private.okd4.{{ .Values.region }}.snappcloud.io"
  port:
    targetPort: {{ $.Values.service.port }}
  to:
    kind: Service
    name: {{ include "snappcloud-status-backend.fullname" $ }}
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
