logger:
  development: true
  level: "info"
  encoding: "console"
querier:
  request_interval: 5s
  request_timeout: 1s
  thanos_frontend: "http://localhost:9090/api/v1/query"
  services:
    - order: 1
      name: "Pass"
      queries:
        disruption: 'up{job="node-exporter"}'
        outage: 'up{job="node-exporter"}'
